import type { WhatsAppAutoReplyRule } from "@/lib/db/types"

/** Rótulos exibidos no painel (Configurações → Notificações). */
export const WHATSAPP_AUTO_REPLY_RULE_LABELS: Record<string, string> = {
  endereco: "Endereço / como chegar",
  confirmar: "Confirmar horário ou vaga",
  lista_espera: "Lista de espera",
  cancelar_remarcar: "Cancelar / remarcar",
  servicos: "Serviços e preços",
  funcionamento: "Horário de funcionamento",
  horario: "Meu horário (agendamento)",
  profissional_agendamento: "Profissional do meu horário",
  profissionais: "Profissionais da casa",
  unidades: "Unidades / filiais",
  agendar: "Link para agendar",
}

export const DEFAULT_WHATSAPP_AUTO_REPLY_RULES: WhatsAppAutoReplyRule[] = [
  {
    id: "endereco",
    enabled: true,
    keywords: [
      "endereço",
      "endereco",
      "indereço",
      "indereco",
      "onde fica",
      "onde é",
      "onde e",
      "localização",
      "localizacao",
      "como chegar",
      "qual endereço",
      "qual endereco",
      "qual o endereço",
      "qual o endereco",
    ],
    reply_template: "{{barbearia}}\n{{endereco}}\n{{maps}}",
  },
  {
    id: "confirmar",
    enabled: true,
    keywords: [
      "confirmar",
      "confirmo",
      "confirmado",
      "estarei lá",
      "estarei la",
      "pode confirmar",
      "confirmar horário",
      "confirmar horario",
      "confirmar vaga",
    ],
    reply_template: "{{confirmar_resposta}}",
  },
  {
    id: "lista_espera",
    enabled: true,
    keywords: [
      "lista de espera",
      "lista espera",
      "fila de espera",
      "minha fila",
      "estou na fila",
      "vaga disponível",
      "vaga disponivel",
      "confirmar lista",
    ],
    reply_template: "{{lista_espera}}",
  },
  {
    id: "cancelar_remarcar",
    enabled: true,
    keywords: [
      "cancelar",
      "desmarcar",
      "remarcar",
      "mudar horário",
      "mudar horario",
      "trocar horário",
      "trocar horario",
      "alterar horário",
      "alterar horario",
    ],
    reply_template: "{{cancelar_remarcar}}",
  },
  {
    id: "servicos",
    enabled: true,
    keywords: [
      "preço",
      "preco",
      "preços",
      "precos",
      "valor",
      "valores",
      "quanto custa",
      "tabela",
      "serviços",
      "servicos",
      "o que vocês fazem",
      "o que voces fazem",
    ],
    reply_template: "{{lista_servicos}}",
  },
  {
    id: "funcionamento",
    enabled: true,
    keywords: [
      "horário de funcionamento",
      "horario de funcionamento",
      "que horas abre",
      "que horas fecha",
      "horario de abertura",
      "abre que horas",
      "fecha que horas",
      "funcionamento",
      "abre domingo",
      "abre sabado",
    ],
    reply_template: "{{horario_funcionamento}}",
  },
  {
    id: "horario",
    enabled: true,
    keywords: [
      "meu horário",
      "meu horario",
      "tenho agendamento",
      "meu agendamento",
      "quando é",
      "quando e",
      "qual meu horario",
      "qual meu horário",
      "qual é o meu horário",
      "qual e o meu horario",
    ],
    reply_template: "{{proximo_agendamento}}",
  },
  {
    id: "profissional_agendamento",
    enabled: true,
    keywords: [
      "quem vai me atender",
      "quem me atende",
      "qual profissional vai me atender",
      "qual profissional no meu agendamento",
      "quem é meu barbeiro",
      "quem e meu barbeiro",
      "quem é meu profissional",
      "quem e meu profissional",
      "com quem é meu horário",
      "com quem e meu horario",
      "com quem marquei",
      "meu barbeiro",
      "meu profissional",
    ],
    reply_template: "{{profissional_agendamento}}",
  },
  {
    id: "profissionais",
    enabled: true,
    keywords: [
      "qual profissional disponível",
      "qual profissional disponivel",
      "profissionais disponíveis",
      "profissionais disponiveis",
      "quem está disponível",
      "quem esta disponivel",
      "quais profissionais",
      "lista de profissionais",
      "quem atende aí",
      "quem atende ai",
      "quem trabalha aí",
      "quem trabalha ai",
    ],
    reply_template: "{{lista_profissionais}}",
  },
  {
    id: "unidades",
    enabled: true,
    keywords: ["quantas lojas", "quantas unidades", "unidades", "filiais", "lojas", "quantas filiais"],
    reply_template: "{{lista_unidades}}",
  },
  {
    id: "agendar",
    enabled: true,
    keywords: [
      "agendar",
      "agendamento",
      "fazer agendamento",
      "fazer um agendamento",
      "quero agendar",
      "gostaria de agendar",
      "como agendo",
      "como faço para agendar",
      "como faco para agendar",
      "link agendamento",
      "link para agendar",
      "marcar horário",
      "marcar horario",
      "marcar um horário",
      "marcar um horario",
      "quero marcar",
      "marcação",
      "marcacao",
      "quero cortar",
      "horário disponível",
      "horario disponivel",
      "tem horário",
      "tem horario",
      "tem horario para hoje",
      "tem horário para hoje",
      "horario para hoje",
      "horário para hoje",
      "tem horario hoje",
      "tem horário hoje",
      "tem vaga",
      "tem vaga hoje",
      "horarios disponiveis",
      "horários disponíveis",
      "tem horario amanha",
      "tem horário amanhã",
    ],
    reply_template:
      "Para ver horários disponíveis e agendar, acesse:\n{{link_agendamento}}",
  },
]
